clear;clc;
liftingForces = importfile('liftingForce_all.csv');
bendingMoments = importfile('bendingMoment_all.csv');

AC_locations = bendingMoments(:,2:2:10) ./ liftingForces(:,2:2:10);
alphaValues = bendingMoments(:,1:2:10);
wingProfiles = [1000 1004 1152 1154 1304];

figure()
for q = 1:length(wingProfiles)
    ACx_alpha = [alphaValues(:,q) AC_locations(:,q)];
    ACx_alpha(isnan(ACx_alpha(:,1)), :) = [];
    save(sprintf('ACx_alpha_%d.mat', wingProfiles(q)), "ACx_alpha");
    plot(ACx_alpha(:,1), ACx_alpha(:,2))
    hold on
end
%% functions
function liftingForceall = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LIFTINGFORCEALL = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LIFTINGFORCEALL = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  liftingForceall = importfile("C:\Users\Carson\OneDrive - North Carolina State University\iSSRL\Research\Morphing Wing\XFLR\data\liftingForce_all.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jul-2023 12:58:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alpha", "kite_1000_T10_8M_sLLT", "Var3", "Alpha1", "kite_1004_T10_8M_sLLT", "Var6", "Alpha2", "kite_1152_T10_8M_sLLT", "Var9", "Alpha3", "kite_1154_T10_8M_sLLT", "Var12", "Alpha4", "kite_1304_T10_8M_sLLT"];
opts.SelectedVariableNames = ["Alpha", "kite_1000_T10_8M_sLLT", "Alpha1", "kite_1004_T10_8M_sLLT", "Alpha2", "kite_1152_T10_8M_sLLT", "Alpha3", "kite_1154_T10_8M_sLLT", "Alpha4", "kite_1304_T10_8M_sLLT"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var6", "Var9", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var6", "Var9", "Var12"], "EmptyFieldRule", "auto");

% Import the data
liftingForceall = readtable(filename, opts);
liftingForceall = table2array(liftingForceall);
end